---
title: "data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readtext)
library(stringr)
library(readxl)
```


read in z alizedeh sani
```{r}
z<- read_excel("Zdataset.xlsx", sheet=1)

# column names are bad- change them
names(z) <- make.names(names(z))


# change z ali sani chr to factor
z$Sex<-as.factor(z$Sex)
z$Current.Smoker<-as.factor(z$Current.Smoker)
z$EX.Smoker<-as.factor(z$EX.Smoker)
z$Cath<-as.factor(z$Cath)
z$Obesity <-as.factor(z$Obesity)
z$CRF <-as.factor(z$CRF)
z$CVA <-as.factor(z$CVA)
z$Airway.disease <-as.factor(z$Airway.disease)
z$Thyroid.Disease <-as.factor(z$Thyroid.Disease)
z$CHF <-as.factor(z$CHF)
z$DLP <-as.factor(z$DLP)
z$Weak.Peripheral.Pulse <-as.factor(z$Weak.Peripheral.Pulse)
z$Lung.rales <-as.factor(z$Lung.rales)
z$Systolic.Murmur <-as.factor(z$Systolic.Murmur)
z$Diastolic.Murmur <-as.factor(z$Diastolic.Murmur)
z$Dyspnea <-as.factor(z$Dyspnea)
z$Atypical <-as.factor(z$Atypical)
z$Nonanginal <-as.factor(z$Nonanginal)
z$Exertional.CP <-as.factor(z$Exertional.CP)
z$LowTH.Ang <-as.factor(z$LowTH.Ang)
z$LVH <-as.factor(z$LVH)
z$Poor.R.Progression <-as.factor(z$Poor.R.Progression)
z$BBB <-as.factor(z$BBB)
z$VHD <-as.factor(z$VHD)


# make test and training set
set.seed(1111) #random seed   
train.row = sample(1:nrow(z), 0.7*nrow(z))  
data.train = z[train.row,]  
data.test = z[-train.row,]


```

Hungary data
```{r}
# this is the small 14 variable set
h<- read.table("processed.hungarian.data")

# split columns

h<-h %>% separate(V1, c("Age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "num"))

write.csv(h,'hungary_small.csv')
```

```{r}
# large set

# this is the small 76 variable set

#this line works
h<-readtext("hungarian.data")
h<- h[-1]


#split rows

h<-h %>% 
  separate_rows(text, sep = "name")
# split columns

# remove \n from row2:

h<-h %>%
  mutate(text = str_replace(text, "\n",""))


h<-h %>% separate(text, c("id","ccf", "age" ,"sex", "painloc" ,"painexer" ,"relrest" ,"pncaden" ,"cp", "trestbps","htn" , "chol","smoke" ,"cigs" , "years" ,"fbs", "dm" ,"famhist" ,"restecg", "ekgmo" ,"ekgday" , "ekgyr" ,"dig" ,"prop" ,"nitr" ,"pro" ,"diuretic" ,"proto" ,"thaldur" , "thaltime" ,"mets" ,"thalach","thalrest" ,"tpeaksbps" ,"tpeaksbpd" , "dummy" ,"trestbpd" ,"exang","xhypo" , "oldpeak", "slope", "r1dv5" ,"r1dv5e" ,"ca", "restckm" ,"exerckm" ,"restef" ,"restwm" ,"exeref", "exerwm"  ,"thal", "thalsev" , "thalpul" ,"earlobe" ,"cmo" ,"cday" ,"cyr" ,"num", "lmt" ,"ladprox" ,"laddist" , "diag" ,"cxmain" , "ramus" ,"om1" ,"om2" ,"rcaprox" ,"rcadist" ,"lvx1" ,"lvx2" ,"lvx3" ,"lvx4" ,"lvf" ,"cathef" ,"junk"))

write.csv(h,'hungary_large.csv')
```

Cleveland set
```{r}
# large set

# this is the small 76 variable set

#this line works
c<-readtext("cleveland.data")
c<- c[-1]


#split rows

c<-c %>% 
  separate_rows(text, sep = "name")
# split columns

# remove \n from row2:

c<-c %>%
  mutate(text = str_replace(text, "\n",""))


c<-c %>% separate(text, c("id","ccf", "age" ,"sex", "painloc" ,"painexer" ,"relrest" ,"pncaden" ,"cp", "trestbps","htn" , "chol","smoke" ,"cigs" , "years" ,"fbs", "dm" ,"famhist" ,"restecg", "ekgmo" ,"ekgday" , "ekgyr" ,"dig" ,"prop" ,"nitr" ,"pro" ,"diuretic" ,"proto" ,"thaldur" , "thaltime" ,"mets" ,"thalach","thalrest" ,"tpeaksbps" ,"tpeaksbpd" , "dummy" ,"trestbpd" ,"exang","xhypo" , "oldpeak", "slope", "r1dv5" ,"r1dv5e" ,"ca", "restckm" ,"exerckm" ,"restef" ,"restwm" ,"exeref", "exerwm"  ,"thal", "thalsev" , "thalpul" ,"earlobe" ,"cmo" ,"cday" ,"cyr" ,"num", "lmt" ,"ladprox" ,"laddist" , "diag" ,"cxmain" , "ramus" ,"om1" ,"om2" ,"rcaprox" ,"rcadist" ,"lvx1" ,"lvx2" ,"lvx3" ,"lvx4" ,"lvf" ,"cathef" ,"junk"))

write.csv(c,'cleveland_large.csv')
```

switzerland set
```{r}
# large set

# this is the small 76 variable set

#this line works
c<-readtext("switzerland.data")
c<- c[-1]


#split rows

c<-c %>% 
  separate_rows(text, sep = "name")
# split columns

# remove \n from row2:

c<-c %>%
  mutate(text = str_replace(text, "\n",""))


c<-c %>% separate(text, c("id","ccf", "age" ,"sex", "painloc" ,"painexer" ,"relrest" ,"pncaden" ,"cp", "trestbps","htn" , "chol","smoke" ,"cigs" , "years" ,"fbs", "dm" ,"famhist" ,"restecg", "ekgmo" ,"ekgday" , "ekgyr" ,"dig" ,"prop" ,"nitr" ,"pro" ,"diuretic" ,"proto" ,"thaldur" , "thaltime" ,"mets" ,"thalach","thalrest" ,"tpeaksbps" ,"tpeaksbpd" , "dummy" ,"trestbpd" ,"exang","xhypo" , "oldpeak", "slope", "r1dv5" ,"r1dv5e" ,"ca", "restckm" ,"exerckm" ,"restef" ,"restwm" ,"exeref", "exerwm"  ,"thal", "thalsev" , "thalpul" ,"earlobe" ,"cmo" ,"cday" ,"cyr" ,"num", "lmt" ,"ladprox" ,"laddist" , "diag" ,"cxmain" , "ramus" ,"om1" ,"om2" ,"rcaprox" ,"rcadist" ,"lvx1" ,"lvx2" ,"lvx3" ,"lvx4" ,"lvf" ,"cathef" ,"junk"))

write.csv(c,'switzerland_large.csv')
```


long beach set
```{r}
# large set

# this is the small 76 variable set

#this line works
c<-readtext("long-beach-va.data")
c<- c[-1]


#split rows

c<-c %>% 
  separate_rows(text, sep = "name")
# split columns

# remove \n from row2:

c<-c %>%
  mutate(text = str_replace(text, "\n",""))


c<-c %>% separate(text, c("id","ccf", "age" ,"sex", "painloc" ,"painexer" ,"relrest" ,"pncaden" ,"cp", "trestbps","htn" , "chol","smoke" ,"cigs" , "years" ,"fbs", "dm" ,"famhist" ,"restecg", "ekgmo" ,"ekgday" , "ekgyr" ,"dig" ,"prop" ,"nitr" ,"pro" ,"diuretic" ,"proto" ,"thaldur" , "thaltime" ,"mets" ,"thalach","thalrest" ,"tpeaksbps" ,"tpeaksbpd" , "dummy" ,"trestbpd" ,"exang","xhypo" , "oldpeak", "slope", "r1dv5" ,"r1dv5e" ,"ca", "restckm" ,"exerckm" ,"restef" ,"restwm" ,"exeref", "exerwm"  ,"thal", "thalsev" , "thalpul" ,"earlobe" ,"cmo" ,"cday" ,"cyr" ,"num", "lmt" ,"ladprox" ,"laddist" , "diag" ,"cxmain" , "ramus" ,"om1" ,"om2" ,"rcaprox" ,"rcadist" ,"lvx1" ,"lvx2" ,"lvx3" ,"lvx4" ,"lvf" ,"cathef" ,"junk"))

write.csv(c,'longbeach_large.csv')
```